// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;
import ballerina/test;

configurable http:BearerTokenConfig & readonly authConfig = ?;
ConnectionConfig config = {auth : authConfig};
Client baseClient = check new Client(config, serviceUrl = "https://api.openai.com/v1");

@test:Config {}
isolated function  testCreateTranscription() {
}

@test:Config {}
isolated function  testCreateSpeech() {
}

@test:Config {}
isolated function  testCreateTranslation() {
}
