[package]
distribution = "2201.9.0"
org = "ballerinax"
name = "openai.audio"
version = "@toml.version@"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = [] # TODO: Add keywords
icon = "icon.png" # TODO: Add icon
repository = "https://github.com/e19166/module-ballerinax-openai-audio"

[build-options]
observabilityIncluded = true