[package]
distribution = "2201.9.0"
org = "ballerinax"
name = "openai.audio"
version = "0.1.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = []
icon = "icon.png"
repository = "https://github.com/e19166/module-ballerinax-openai-audio"

[build-options]
observabilityIncluded = true